### ISSUE TITLE
Optimize performance

### ISSUE THREAD

**Issue by raffomania** [lovetoys/lovetoys#21]
http://lua-users.org/wiki/ProfilingLuaCode could be of help.

**Comment by Luminess** [comment]
Love2D uses LuaJIT. According to [this page](http://wiki.luajit.org/NYI) pairs() is not JIT compiled. So any instruction path that uses pairs() would not benefit from the performance improvements from the LuaJIT runtime.

Looking through the code, I believe there are some usage of pairs() that could be replaced ipairs(). Doing so would be a first step to improving overall performance.

**Comment by Nukesor** [comment]
Thx for the advice and the website, it looks really helpful.
We are currently looking into some profiling tools as well, so there will hopefully be some progress on this issue soon.

**Comment by Luminess** [comment]
[LuaJIT v2.1 has a built-in sampling profiler](https://rawgit.com/LuaJIT/LuaJIT/v2.1/doc/ext_profiler.html). One of the output formats it supports looks pretty neat:
```
$ luajit -jp=a spectralnorm.lua 4000
====== spectralnorm.lua ======
 <at>  <at>  3  <at>  <at> 
      | -- contributed by Mike Pall
      | 
      | local function A(i, j)
  10% |   local ij = i+j-1
  25% |   return 1.0 / (ij * (ij-1) * 0.5 + i)
      | end
      | 
      | local function Av(x, y, N)
      |   for i=1,N do
      |     local a = 0
  32% |     for j=1,N do a = a + x[j] * A(i, j) end
      |     y[i] = a
      |   end
      | end
 <at>  <at>  18  <at>  <at> 
      | local function Atv(x, y, N)
      |   for i=1,N do
      |     local a = 0
  32% |     for j=1,N do a = a + x[j] * A(j, i) end
      |     y[i] = a
      |   end
      | end
```

**Comment by raffomania** [comment]
Wow, we didn't know about that, thanks a lot. @Nukesor and me are still looking for some time for this ticket, if in the meantime you find out more feel free to open a PR or comment again :)

**Comment by Luminess** [comment]
It also has [a feature where you could label sections of code as zones for an easier to read profiler output](https://rawgit.com/LuaJIT/LuaJIT/v2.1/doc/ext_profiler.html#jit_zone). E.g. a game could make use of an "AI" zone, a "PHYS" zone, etc.
