### ISSUE TITLE
create abstract data structure for engine internals

### ISSUE THREAD

**Issue by raffomania** [lovetoys/lovetoys#27]
We have two different sets of data that the engine manages:

- A collection of entities that need to be filtered by their component constellations.
- A collection of Systems that represent one or more constellations of required components.

To clean up the code it would be nice to create one or more specialized data structures to handle those two collections outside of the engine.

### questions
- do we create separate data structures for entities and systems or does one structure manage both? 
- should the structure be able to filter systems by activeness/inactiveness?

### needed functionality
- fast lookup of systems whose requirements a given entity meets
  - does not necessarily need to be exposed, could be handled automatically on entity adding, removing etc
- usual methods: add, remove, getAll, hasEntity, hasSystem etc.

**Comment by Luminess** [comment]
How much performance is needed? More information is needed to design an implementation for it.

A good start would be to write down the planned interface for each structure; including its methods, their respective arguments, along with what they should return. Preferably have this written out in a concise and documented format like [a Java Interface](https://docs.oracle.com/javase/tutorial/java/IandI/createinterface.html). That should give a broad overview of the goal.
