### ISSUE TITLE
Don't use globals.

### ISSUE THREAD

**Issue by xpol** [lovetoys/lovetoys#30]
Can lovetoys not use globals.

eg.

```lua
local M = class('xxxx')

...

return M
```

**Comment by xpol** [comment]
I have add a pull request #31 for you.

**Comment by Nukesor** [comment]
We are planning to add a configuration file, in which this will be adjustable. Until then lovetoys will be global by default.

**Comment by rosshadden** [comment]
Out of curiosity, why would you want this to be adjustable?  Globals are an antipattern.  If someone ever has a situation in which they need a global (for some reason), they can simply write something like this, depending on how you export the modules:

```lua
Entity, Component, System, etc = require('lovetoys')
```

**Comment by rosshadden** [comment]
Actually a much better solution than what I previously suggested would be to have a file that exports all things as globals.  So anyone that wants them can 

```lua
require('lovetoys.global')
```

(or whatever you call it), and anyone that wants to import specific modules as they are needed can:

```lua
local Entity = require('lovetoys.src.Entity')
```

That way no config setting is necessary, and everyone wins.

**Comment by raffomania** [comment]
We fixed this in the 0.3.0 release, see the configuration section in the README for details :)

**Comment by rosshadden** [comment]
Awesome!

**Comment by xpol** [comment]
:+1:
