### ISSUE TITLE
Should be able to require library using dot notation as path seperator

### ISSUE THREAD

**Issue by Luminess** [lovetoys/lovetoys#41]
IE: This will error out since the pattern matching in [line 2 of lovetoys.lua](https://github.com/lovetoys/lovetoys/blob/master/lovetoys.lua#L2) matches for "/" and not ".".
```lua
require('vendor.lovetoys.lovetoys')
```

It's more portable to use dot notation as different OSs use either "/" or "\" for path seperators.

**Comment by raffomania** [comment]
Should be fixed, thanks for reporting.
