### ISSUE TITLE
Treating systems as objects does not make sense

### ISSUE THREAD

**Issue by Luminess** [lovetoys/lovetoys#48]
By definition, a system in a Entity-Component System framework is a stateless processor for its declared components in an entity. This boils down to basically a function to process the entity along with some metadata. Treating systems as an object when you really are only going to instantiate a system once is unneeded.

Helps with #21

**Comment by raffomania** [comment]
You're right about that. But I think reducing systems to mere functions would lead to drawbacks regarding flexibility. As a class, a system can override default behavior and easily manipulate entities and Metadata obtained from the engine. E.g. A system responsible for drawing sprites could sort it's entities by their z-index.  Another possibility is to calculate and store computed parameters in its constructor.

How would you give that flexibility back when using only functions?

**Comment by raffomania** [comment]
I don't see any reasonable solutions to this as of now. Closing this.
