### ISSUE TITLE
Travis-CI caches project files

### ISSUE THREAD

**Issue by Luminess** [lovetoys/lovetoys#50]
Just noticed that [here](https://travis-ci.org/lovetoys/lovetoys/jobs/109366473#L209).

**Comment by raffomania** [comment]
We just emptied the travis cache by hand. As we are not installing lovetoys via luarocks anymore, this should fix the issue without additional code.

**Comment by Luminess** [comment]
Just checked [the latest Travis-CI build (Job #116.2) log](https://travis-ci.org/lovetoys/lovetoys/jobs/109860484). On [line 205](https://travis-ci.org/lovetoys/lovetoys/jobs/109860484#L205), it's still storing the changes to the repository.

> we are not installing lovetoys via luarocks anymore

Since when did this change occur? So far, the project is still being made using LuaRocks in  [.travis.yml#L19](https://github.com/lovetoys/lovetoys/blob/095f7893e0fbaac7b7e2622bae97bf800cdcf4f3/.travis.yml#L19).

This issue should be addressed due to the possibility of the deletion of files in the project not reflecting in the cache, resulting in unpredictable side effects including unreliable test results.

**Comment by raffomania** [comment]
Oh, thanks, I completely overlooked that line. Is there a reason we are installing the lovetoys using luarocks? Does this help to test the rockspec against regressions? `busted` should definitely work without the installation.

**Comment by raffomania** [comment]
We fixed this by removing the luarocks install. We're trying to keep the travis config as simple as possible.
