### ISSUE TITLE
module 'src.namespace' not found

### ISSUE THREAD

**Issue by rosshadden** [lovetoys/lovetoys#52]
After updating to the latest version, I get the following error when requiring lovetoys:

```
Error: vendor/lovetoys/lovetoys.lua:4: module 'src.namespace' not found:
        no field package.preload['src.namespace']
        no 'src/namespace' in LOVE game directories.
        no file 'src/namespace.so' in LOVE paths.
        no file './src/namespace.lua'
        no file '/usr/share/luajit-2.0.4/src/namespace.lua'
        no file '/usr/local/share/lua/5.1/src/namespace.lua'
        no file '/usr/local/share/lua/5.1/src/namespace/init.lua'
        no file '/usr/share/lua/5.1/src/namespace.lua'
        no file '/usr/share/lua/5.1/src/namespace/init.lua'
        no file './src/namespace.so'
        no file '/usr/local/lib/lua/5.1/src/namespace.so'
        no file '/usr/lib/lua/5.1/src/namespace.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './src.so'
        no file '/usr/local/lib/lua/5.1/src.so'
        no file '/usr/lib/lua/5.1/src.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vendor/lovetoys/lovetoys.lua:4: in main chunk
        [C]: in function 'require'
        main.lua:2: in main chunk
        [C]: in function 'require'
        [string "boot.lua"]:428: in function <[string "boot.lua"]:274>
        [C]: in function 'xpcall'
```

Note that I have lovetoys cloned as a submodule at `vendor/lovetoys`, and am thus requiring `vendor/lovetoys/lovetoys`.  I have tried requiring it with dots as well.  This used to work until v0.3.0.

**Comment by Nukesor** [comment]
Hey rosshadden, 

We changed the way lovetoys are beeing required.
Now there is a lovetoys.initialize function, that can accept configs. 
Please look at the `Configuration` section of our README and if there is a version change, take a look at our CHANGELOG ;).

If you've already done this and there is still a bug, it'd be great if you could provide your setup code.

**Comment by rosshadden** [comment]
Yeah I've already done that.  The error actually occurs on `require` of lovetoys, so whether or not I call `initialize` isn't relevant by that point.

**Comment by rosshadden** [comment]
I can recreate this with the following minimal `main.lua` file:

```lua
lovetoys = require('vendor.lovetoys.lovetoys')
lovetoys.initialize({})
```

**Comment by Nukesor** [comment]
Ok, I can reproduce this. Stay tuned we're debugging.
Sorry for the inconvenience.

**Comment by rosshadden** [comment]
No problem, I'm happy to see you guys working on this again!

**Comment by Nukesor** [comment]
Ok. I justed fixed this. Our example is working again as well.
There was a problem with relative imports in the love environment.
Thanks for the report :+1: 
Have a nice day :)

**Comment by rosshadden** [comment]
Works great, thanks for fixing so quickly.
