### ISSUE TITLE
Question: systems can only update or draw?

### ISSUE THREAD

**Issue by mpicard** [lovetoys/lovetoys#61]
Hi there I'm new to ESC so maybe this is obvious but why can't I have a System that has both an update() and a draw() function? 

For example I have an animation System that needs to both call update on the animation and draw the animation frame, it would be nice to do this in one system no? I could be designing this totally wrong

**Comment by raffomania** [comment]
Hi, you can definitely have a system that does both, you just have to register it twice. Have a look [at the relevant documentation](https://github.com/lovetoys/lovetoys#engineaddsystemsystem-type).

**Comment by mpicard** [comment]
Ah you are correct I must have missed that last bit, sorry! Thanks for the help @raffomania
