### ISSUE TITLE
Error when initializing lovetoys

### ISSUE THREAD

**Issue by Substr** [lovetoys/lovetoys#63]
Hi, I'm getting the following error when initializing lovetoys. Using the latest .zip download, running with the latest love2d version.

**Error:**
`Error: lib/lovetoys/src/events/ComponentAdded.lua:12: attempt to call field 'class' (a nil value)`

**minimal main.lua:**
```
lovetoys = require('lib.lovetoys.lovetoys')
lovetoys.initialize({
    globals = true,
    debug = true
})
```

Did a bit of debugging, breaking on this line:

ComponentAdded.lua:12
`local ComponentAdded = require(folderOfThisFile .. '.namespace').class("ComponentAdded")`

It seems like it's trying to include the empty table from namespace.lua which was previously populated with various things (including 'class') in lovetoys.lua `populateNamespace()`

however it doesn't seem like it's actually referring to the same table:
```
>>> require(folderOfThisFile .. '.namespace')
{} --[[table: 0x0b3834c8]]

>>> lovetoys  -- This is supposed to be the same table as the one included from namespace.lua
{class = {Object = "class Object", _DESCRIPTION = "Object --  (TRIMMED) [[..skipped..]] end}} --
[[table: 0x08c47738]]
```

**Comment by Substr** [comment]
I seem to have found the problem, but not the reason for it:

`lovetoys = require("lib.lovetoys.lovetoys")`  // This causes the error mentioned above
`lovetoys = require("lib/lovetoys/lovetoys")`  // This works 

Hopefully this helps you resolve the bug.

**Comment by raffomania** [comment]
Fixed on master. We will issue a bugfix release soon. Thanks for reporting!
