### ISSUE TITLE
Docs outdated? Init code doesn't seem to work

### ISSUE THREAD

**Issue by brazorf** [lovetoys/lovetoys#68]
This one is not working
```
local lovetoys = require("lovetoys.lovetoys")
lovetoys.initialize()

local entity = lovetoys.Entity()
local system = lovetoys.System()
local engine = lovetoys.Engine()
local component = lovetoys.Component()
local eventManager = lovetoys.EventManager()
```

Error: `Error: main.lua:7: attempt to call field 'Component' (a table value)
stack traceback:`

**Comment by jkbz64** [comment]
Yeah, this is probably mistake/old code. Component is simply just a table with all registered components and factory function to create and/or register them. To create component you can simply use Component's table create syntax 
``` -- Create a Color component with the default color set to blue
local Color = Component.create("Color",
    {"r", "g", "b"},
    {r = 0, g = 0, b = 255})
```
or do it manually like this
```
local Color = class('Color')
-- When you create component 'manually' remember to use Component's table function to register it otherwise you wont be able to use them in some places( this doesn't have to be done in syntax i show you above because Component.Create takes care of it
lovetoys.Component.register(Color)
function Color:initialize(r, g, b)
    local r = r or 0
    local g = g or 0
    local b = b or 255
end
```
Then if u want to create them just write
```
local colorComponent = Color(255, 255, 255)
-- and add it to entity :)
someEntity:add(colorComponent)
```

**Comment by brazorf** [comment]
Thanks, however i'm having hard times trying to figure things out.

```
local lovetoys = require('lovetoys.lovetoys')
lovetoys.initialize()

function love.load()
	local position = lovetoys.Component.create("position", {"x", "y"}, {x = 0, y = 0})
	player = lovetoys.Entity()
	player:add(position)
end
```

`Error: lovetoys/src/Entity.lua:23: attempt to index field 'class' (a nil value)`

*p.s. why the redundant need to specify separately component keys and component defaults?*

**Comment by raffomania** [comment]
Definitely outdated, I'll update this soon. 
Regarding your example, `Component.create` returns a component class, while `player:add` expects an instance. Use it like this:
```
local Position = lovetoys.Component.create("position", {"x", "y"}, {x = 0, y = 0})
	player = lovetoys.Entity()
	player:add(Position(100, 100))
```

**Comment by raffomania** [comment]
I've removed the `Component` and `EventManager` lines from the example in question, I think the other three lines demonstrate the middleclass constructors well enough. Let me know if other parts of the docs need clarification or additional examples!

**Comment by brazorf** [comment]
@raffomania will do. Thanks!

**Comment by brazorf** [comment]
@raffomania check this out https://github.com/lovetoys/lovetoys/pull/70
