### ISSUE TITLE
main.lua file of the lovetoys example game linke at readme file is broken

### ISSUE THREAD

**Issue by ShmooliKipoD** [lovetoys/lovetoys#79]
main.lua file of the lovetoys example game link at readme file is broken.

when clicking getting 404 error

**Comment by Nukesor** [comment]
@raffomania Did we nuke the example project :D? Can't remember doing so...
Should we remove the link or point it to the preset repo?

**Comment by ShmooliKipoD** [comment]
Hi, 

I don't think there is an issue with the example folder, I just think it was moved by the readme didn't update.

the readme is pointing to:
https://github.com/lovetoys/example/blob/master/main.lua

while it should point to :
https://github.com/lovetoys/lovetoys/blob/master/example/main.lua

**Comment by raffomania** [comment]
thanks!
