### ISSUE TITLE
How do you manually create classes?

### ISSUE THREAD

**Issue by lukehayes** [lovetoys/lovetoys#82]
I'm using Lovetoys and I have a working project until I started to create component classes manually.

I have a simple sprite class:

```
local lovetoys = require('libs.lovetoys')
local Sprite = lovetoys.class("Sprite")

function Sprite:intialize(path)
    print("Sprite initialized")
    self.path = path
    self.image = love.graphics.newImage(self.path)
end

return Sprite
```

and I import it into my `main.lua` like this:

`local Sprite = require('components.Sprite')`

When I read through the documentation, I think I need to call `Component.register()` to make the component available so I write:

```
function love.load()

    -- Simplified version of my love.load()
    engine = Engine()
    Component.register('components.Sprite')
end
```
This triggers an error:
`Error: libs/lovetoys/src/Component.lua:31: table index is nil`

I know I can use `Component.create()` but ideally I would like to use the `middleclass` style of creating classes.

What am I doing wrong here?

**Comment by raffomania** [comment]
Hmm, it seems like the docs are outdated. Sorry for that. Looking at the source, it seems like `Component.register` expects the class itself, e.g.

```lua
local lovetoys = require('libs.lovetoys')
local Sprite = lovetoys.class("Sprite")

function Sprite:intialize(path)
    print("Sprite initialized")
    self.path = path
    self.image = love.graphics.newImage(self.path)
end

lovetoys.Component.register(Sprite)
```
